# Generated by Django 4.1.7 on 2023-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=None),
        ),
    ]
