# Generated by Django 4.1.7 on 2023-04-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_order_order_details_order_order_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'CustomerUser', 'verbose_name_plural': 'CustomerUsers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
