# Generated by Django 4.1.7 on 2023-04-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'Customer User', 'verbose_name_plural': 'Customer Users'},
        ),
    ]
