# Generated by Django 4.1.7 on 2023-04-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_customeruser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='order_by',
        ),
    ]
