# Generated by Django 4.1.7 on 2023-04-01 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0006_rename_user_order_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_by',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
