# Generated by Django 4.1.7 on 2023-04-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
